### ISSUE TITLE
Unknown blueprint: ember-i18n

### ISSUE THREAD

**Issue by mk-conn** [jamesarosen/ember-i18n#197]
Followed the instruction on installing for ember-cli via node I get the error 

$ ember generate ember-i18n

--> Unknown blueprint: ember-i18n

version: 0.2.0-beta.1
node: 0.12.0
npm: 2.1.8
emberjs: 1.10

**Comment by jamesarosen** [comment]
cc @pjmorse @chrmod 

Does this have to do with it being a beta release? Or maybe I need to push to NPM?

**Comment by pjmorse** [comment]
Ah, I was going to look at this and it slipped my mind.

This isn't an issue with finding and downloading ember-i18n; it's an issue with ember-cli and the configuration we did, I think. (Although we should probably push to NPM, because I was testing by giving ember-cli my local path to the project, and it doesn't work without that:

    pjmorse$ ember install:addon ember-i18n
    version: 0.1.12
    Installed packages for tooling via npm.
    Install failed. Could not find addon with name: ember-i18n

What worked in development was `ember install:addon ~/Projects/ember-i18n`.

Anyway, the error @mk-conn is seeing is one ember-cli produces. When the addon is installed, it provides a certain number of blueprints (analogous to Rails' generators, I think). The blueprint with the same name as the addon is special, because it will be run at install time. This error suggests either the installation was incomplete somehow (no blueprint present)... or it's just superfluous, because @chrmod 's comments on #192 make me think that once we're at the point of trying to run blueprints, we already have ember-i18n installed.

**Comment by kevvvvv** [comment]
This is still present, even on a fresh install. Was this reported to ember-cli team?

**Comment by beastmst** [comment]
any solution on this?

**Comment by RomainLanz** [comment]
Bump

**Comment by locks** [comment]
What version of the addon do you have specified?

**Comment by RomainLanz** [comment]
I just follow instructions.

````
npm install ember-i18n --save-dev
````

````
"ember-i18n": "^3.0.0-beta.4"
````

**Comment by chrmod** [comment]
@jamesarosen it seems that version distributed via npm is not really what it introduce itself.

Try to run `npm install ember-i18n` and see what you find in `node_modules/ember-i18n` - it so some 2.x version, but with different version name. (there is neither `lib/ember-addon`, nor 'ember-addon' secion in package.json)

Please push proper codebase to npm registry. 

PS. version published by bower works properly.

**Comment by jamesarosen** [comment]
I just pushed 3.0.0. Can you try that?

**Comment by chrmod** [comment]
works good here :+1: 

can someone cross verify?

**Comment by koenig** [comment]
(y) had the same issue and it's gone after reinstalling 3.0.0

**Comment by kevvvvv** [comment]
Fixed for me too.

**Comment by locks** [comment]
Thank you for the feedback :)
