### ISSUE TITLE
Updating to 3.1.1 from 3.1.0 causes tests to fail

### ISSUE THREAD

**Issue by jrjohnson** [jamesarosen/ember-i18n#212]
This may be an issue with my testing setup, but after updating to the latest version all of my components which use TranslateableProperties are failing tests with the message

> Assertion failed: You have turned on testing mode, which disabled the run-loop's autorun. You will need to wrap any code with asynchronous side-effects in an Ember.run

I'm guessing this has to do with #207, but I'm not sure how to confirm.  Do I need to wrap the setup for all of my component tests in an Ember.run?  Is anyone else having this problem?

**Comment by jamesarosen** [comment]
I hadn't tried this out in the test mode of an app. My guess is that this will require initializing components in an `Ember.run` loop.

@MattNguyen what's your approach been?

**Comment by simonihmig** [comment]
I can confirm this. Wrapping the unit test in Ember.run seems to fix it!
However having to fix all unit tests just because of using this mixin does not feel right...

**Comment by jamesarosen** [comment]
I'm torn on this. On the one hand, I know how frustrating it is to have to change a bunch of tests. On the other, they were relying on what is essentially a bug. `set`s should always be wrapped in `run` in tests. `TranslateableProperties` does a series of `set`s.

**Comment by jrjohnson** [comment]
I'm ok with the solution.  I agree it seems wrong and it's not super fun to do, but I'm guessing there isn't any way to get around this.

I do think this should have been released as 3.2 since this is essentially a breaking change.

**Comment by simonihmig** [comment]
@jamesarosen If I understand it right, the `set`s are not the problem, but https://github.com/jamesarosen/ember-i18n/blob/master/lib/i18n.js#L129-L131. And you were never supposed to call `this.subject()` (that's were the exception comes from) in a run loop, so the pattern of testing a ember-i18n-enabled class would be pretty non-standard here!

In my case a couple of plain stupid component tests, that were generated by ember-cli's default component test blueprint (https://github.com/ember-cli/ember-cli/blob/master/blueprints/component-test/files/tests/unit/__path__/__test__.js), and never modified, were failing, just because the component was using the mixin and the update to 3.1.1 was made! So actually I don't think we have a solution here. :(

**Comment by jamesarosen** [comment]
I don't mind yanking 3.1.1 and releasing as 3.2.

**Comment by MattNguyen** [comment]
Sorry, a little late to the party. Yes, we've had to wrap object instantiation in `Ember.run`. I can update the readme for this.

@simonihmig - https://github.com/jamesarosen/ember-i18n/pull/199 was merged in to address an issue with using `TranslateableProperties` on ObjectControllers. True, it is not desirable to have to wrap object instantiation  in `Ember.run`. However, when the mixin you're adding overrides init to set up properties on an object, it makes perfect sense to wrap your code in a run loop (independent of #199). If this mixin only provided shared methods and properties, then you would be correct to assert that wrapping your code in a runloop is non-standard.

IMO this issue exposes the danger of 1) object proxying via ObjectController and 2) overriding init to asynchronously setup initial data. Unfortunately I don't see a better way out of this.
