### ISSUE TITLE
Documentation about translations in helpers

### ISSUE THREAD

**Issue by ErunamoJAZZ** [jamesarosen/ember-i18n#246]
Hello!
Great job you have done here, i was reading discussion about this library, because i was migrating a web of ember 1.7 to 1.12 in the last weeks.

I think will be good idea if you add a example like this to the readme:
`{{input placeholder=(t "user.edit.title")}}`

because is a useful and common user case.

o/

**Comment by jamesarosen** [comment]
I like it!

**Comment by mattma** [comment]
This is not a bug, but it is a common use case that I do not see in the documentation.

1. In `locales/en/translations.js` contains several static key/value pair rules.
2. I have a validation component, simply show the error message on validation errors.
3. Some of validation error comes from local, for example, password strength is not reached to certain strength, it won't send to the server, since client side will return the error message. 
4. In this case, I do have a 'key/value' defined in `locales/en/translations.js`. 
5. In my 'validation component hbs' file, i use `{{t message}}`. Error message shows up is fine.

6. If the validation passed, it sends to the server, server does the evaluation. For example, password is not correct, server send back an JSON payload like `{message: 'username or password is not correct'}`,
It will be displayed in the same 'validation component hbs' file, via `{{t message}}`.
7. in this case, `message` value is dynamic, Does Client or Server side handle the translation?

8. At least, for now, since I am using `{{t message}}`, how should I build up the logic in `locales/en/translations.js` to avoid `missing translation: username or password is not correct` text which displayed on screen. 
9. The problem above is caused by no definition rule in `translation.js` file, is there a way that I could have the same `{{t message}}`, if no rule is matched, simply show whatever server returns without evaluation on translation only for this helper?

**Comment by jamesarosen** [comment]
The JSON-API spec's [section on errors](http://jsonapi.org/format/#errors) suggests that an error from the server look like
```json
{
  "code": "some.error.code",
  "title": "Human-readable text"
}
```
Thus, you could do something like the following in your code
```js
function errorText(i18n, jsonError) {
  if (jsonError.code) { return i18n.t(jsonError.code); }
  return jsonError.title;
}
```

**Comment by mattma** [comment]
how is `errorText` function is being used in the Ember application? Does it define in `locales/en/translations.js`? 

I think I get an idea of general approach. Let me illustrate it so that you could correct me:

`errorText ` function would be evaluated every time when the validation components (in my case) is being triggered. 

1. if there is no server code is being returned, we could safely assume it is simple a client side translation. Everything works as it is.
2. If there is a server code is being return, we simply translate the `jsonError code`. 

One thing that I am still confused is:

Should `Ember-i18n` evaluated every `error code`

export default {
  'validation.500': 'server error',
  'valdation.404': 'page not found'
}

or

Should `Ember-i18n` have no-op on the translation, when `t(jsonError.code)` is being returned from function `errorText`. Simply let server decides which language choice is being used here?

**Comment by jamesarosen** [comment]
> how is errorText function is being used in the Ember application?

It's wherever you are generating error messages. That might be in a controller or a component. It could be in an ember-data adapter. Without knowing a lot more about your app, it's hard to say exactly.

> Does it define in locales/en/translations.js?

No

> Should Ember-i18n evaluated every error code?

I think you mean, "do I call `i18n.t(code)` every time I get a response back from the server?" If so, yes.

> Should Ember-i18n have no-op on the translation, when t(jsonError.code) is being returned from function errorText.

I don't know what this means.

> Simply let server decides which language choice is being used here?

You choose which translations to use by setting `i18n.locale`. That choice could come from the client -- say, by choosing from a menu of available languages. Or it could come from the server -- say by saving some data to the account profile. But the point of ember-i18n is that the server would respond with *codes* where it can and the client would translate.

**Comment by jamesarosen** [comment]
@ErunamoJAZZ I've moved the documentation to the wiki. Check out https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text

**Comment by mattma** [comment]
@jamesarosen I have got it working in my app last night. Well, it was almost 1am and I did not get a chance to update here. I have used exactly the way you suggested in the first reply. 

I do not even need to submit any query param of user's Locale. Server simply return the key what `i18n` expect, then client side will take it over to do the translation. 

This idea is so powerful. I have never imagined that I could do the `i18n` this way. Brilliant! Thanks

**Comment by jamesarosen** [comment]
I'm really glad it's working :)

**Comment by jamesarosen** [comment]
I'm glad it's working for you :)

**Comment by mattma** [comment]
Thanks. Now it is the time to swap Ember-data from RESTAdaper to `JSONAPIAdapter`. 

Good thing is `JSONAPIAdapter` is extending the `RESTAdaper`, By dropping in the `JSONAPIAdapter`, it just works.

Bad part is that I do not have a global error in place, so that I get `'Adapter operation failed'` generic error message to replace my server response. 

Anyway, `Ember-i18n` works as expected. Great project! Heard that `Ember-cli-i18n` from `DockYard` is discussing to merge into the project. Well, from an user perspective, as long as the API stays the same, it is a win-win situation. Thanks for working on it.
