### ISSUE TITLE
With html tag action using ember.js

### ISSUE THREAD

**Issue by NkS90** [jamesarosen/ember-i18n#28]
How can I add html tag with action?

eg:

{{t new.user clickTag="<a {{action showPreview target='view'>Click</a>"}}

**Comment by lalitindoria** [comment]
How would you do this when the anchor text with an action has to appear within a string that has to come from the translation. Something like:

`If you have forgotten your password, <a {{action 'reset'}}>Click Here</a> to reset it.`

**Comment by jamesarosen** [comment]
First, I would use a `<button>`, not an `<a>` for something that _takes an action_ when it is clicked. Links are for _going somewhere_. You won't be able to use an ember action directly on an interpolation since ember-i18n doesn't understand Glimmer.

It's also a little tricky to do in Handlebars because there isn't a built-in `html-safe` helper. You could do it in JavaScript like this:

```js
// app/locales/en/translations.js
{
  'reset-password': {
    button: 'Click Here',
    prompt: 'If you have forgotten your password, {{button}} to reset it.',
  }
}

// app/components/my-component.js
import Component from '@ember/component'
import { computed } from '@ember/object'
import { inject as service } from '@ember/service'
import { htmlSafe } from '@ember/string'

export default Component.extend({
  didInsertElement() {
    this._super(...arguments)
    this.$('.reset').on('click', () => { this.resetPassword() })
  },

  i18n: service(),

  layout: hbs`
    {{passwordPrompt}}
  `,

  passwordPrompt: computed('i18n.locale', function() {
    const i18n = this.get('i18n')
    const button = htmlSafe(`<button class='reset'>${i18n.t('reset-password.button')}</button>`)
    return i18n.t('reset-password.prompt', { button })
  }),

  resetPassword() {
    ...
  }
})
```
