### ISSUE TITLE
Add support for currency formatting

### ISSUE THREAD

**Issue by biscuitvile** [jamesarosen/ember-i18n#283]
This library doesn't feel i18n feature complete to me without currency formatting. Is there currently a roadmap for this? I'm happy to help if you can provide guidance on how you'd like to see this implemented and tested in the project. Thanks!

**Comment by jamesarosen** [comment]
Currency, number, and date-formatting aren't on the roadmap for this library.

If you were to add them, I would suggest defining a `formatNumber` and `formatCurrency` to the `config.js` of each locale:

```js
// app/locales/en/config.js
import { ONE, OTHER } from "./constants";

export default {
  rtl: false,

  pluralForm(n) {
    return n === 1 ? ONE : OTHER;
  },

  formatNumber(n, pad = 0, decimals = null) {
    ...
  },

  formatCurrency(n, unit = "$") {
    return `${unit}${formatNumber(n)}`;
  }
}
```

It might work really well as an extension to ember-i18n.

**Comment by rbemis** [comment]
@jamesarosen Can you point me to documentation/information on how to use this config.s file? For example, what is this "rtl" property? What does it mean when rtl is set to false, when it is set to true? Is the property "pluralForm" a reserved property name that means something special to ember-i18n? What other properties can be set in the config.js file and how are they used?

**Comment by jamesarosen** [comment]
I think the examples in the project are the best documentation: [Arabic](https://github.com/jamesarosen/ember-i18n/blob/master/addon/config/ar.js), [English](https://github.com/jamesarosen/ember-i18n/blob/master/addon/config/en.js), [French](https://github.com/jamesarosen/ember-i18n/blob/master/addon/config/fr.js), [Russian](https://github.com/jamesarosen/ember-i18n/blob/master/addon/config/ru.js), [Chinese](https://github.com/jamesarosen/ember-i18n/blob/master/addon/config/zh.js).

There are only two keys presently:
 * `rtl`: whether the language reads right-to-left
 * `plurlForm`: return the [CLDR](http://cldr.unicode.org/) pluralization code for a given number in the language

**Comment by cea2k** [comment]
Hi @jamesarosen I know this is quite old but, in your suggestion, how are we supposed to use/call the functions "formatNumber" and "formatCurrency" if, apparently, in the addon/utils/locale.js everything but "rtl" and "pluralForm" is ignored?

**Comment by jamesarosen** [comment]
> how are we supposed to use/call the functions

Hmm. Not sure. Maybe you could extend `service:i18n` to know how to look them up? Or maybe the locale object itself should know how to get at its raw `config`?

**Comment by jasonmit** [comment]
Just to add in, I see no reason to rolling your own formatNumber/formatDateTime logic since most browsers support this natively https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

I'm in the process of breaking up ember-intl into compossible chunks (@ember-intl/format-number, @ember-intl/format-datetime).  This will take some time, but in the meantime feel free to roll your own.  Depending on your browser targets, a polyfill may be required.  For that, check out https://github.com/ember-intl/ember-intl/blob/2.x/docs/intljs-polyfill.md#polyfillio

If you want to bundle the polyfill into your vendor.js, that should be available really soon: https://github.com/ember-intl/polyfill.  It's the first part of ember-intl I've started extract out.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
