### ISSUE TITLE
Count attribute is not totally bind to the var

### ISSUE THREAD

**Issue by daminufe** [jamesarosen/ember-i18n#326]
I have this:

```<p>{{t "home.dog" count=dogCount}} {{input value=dogCount type="number"}}</p>```

If I have 1 dog, it shows `dog`, but if I have 2 dogs it shows: `dogs`.
If I put it back to 1 dog, still showing `dogs`

Any ideas?

**Comment by jamesarosen** [comment]
I'm unable to replicate this in a test. Can you show more code -- maybe a failing Ember-Twiddle? Have you verified that the `t` helper receives the updated `count`?

**Comment by daminufe** [comment]
@jamesarosen you can check on my repository here:
https://github.com/daminufe/ember-i18n-test/blob/master/app/templates/application.hbs

Basically it changes in the first change, but then never changes again.

**Comment by jamesarosen** [comment]
The problem is that `count` is changing from `1` to `"2"` to `"1"`. If you look at the [English pluralization rules](https://github.com/jamesarosen/ember-i18n/blob/7a96f1d25bdfe82349b19fb5fd9108416ebf888f/addon/config/en.js), you'll see that it only returns `'ONE'` when `count === 1`.

It might make sense for ember-i18n to coerce `count` to a Number. In the meantime, you can do that yourself with a helper:
```js
// app/helpers/to-number:
export default Ember.Helper.helper(function([ x ]) {
  return +x;
});
```
and
```hbs
{{t "home.dog" count=(to-number dogCount)}}
```

**Comment by daminufe** [comment]
It works :smile:  
Was my issue then 
Thanks @jamesarosen

**Comment by jamesarosen** [comment]
I'm glad! I'm going to reopen this so I remember to do the numeric coercion.
