### ISSUE TITLE
t does not have an i18n on an object inside of an array

### ISSUE THREAD

**Issue by renato04** [jamesarosen/ember-i18n#352]
Hello!

I'm trying to translate a value of an inside of an array this way:

``` javascript
import Ember from 'ember';
import { translationMacro as t } from "ember-i18n";
export default Ember.Controller.extend( {
    fileSystem: Ember.inject.service('filesystem'),
    values:  [{
      name: t('key'),
      value: 'somevalue',
    },
    {
    //another objects
    }]
```

It is throwing this message:
```
Cannot translate key. [object Object] does not have an i18n.
```

Is that correct? What am i doing wrong?

Thank you in Advance.

**Comment by jamesarosen** [comment]
I suggest reading #268.

The problem is that you're using an Ember computed property macro (`t`) on an object (in your case, an object literal within an array literal) that isn't an `Ember.Object` created by the Ember container. The solution is to defer creation of `values` to a computed property so it can be created in the context of your controller:

```js
export default Ember.Controller.extend({
  values: Ember.computed(function() {
    return [
      {
        name: this.get('i18n').t('key'),
        value: 'somevalue'
      }
    ]
  })
});
```

**Comment by renato04** [comment]
@jamesarosen Thank you! It worked
