### ISSUE TITLE
Positional interpolated parameter support

### ISSUE THREAD

**Issue by cfator** [jamesarosen/ember-i18n#357]
Is it possible to use positional parameters instead of named for interpolated?

Named seems superior to positional, however in our case the service we are integrating with that supplies the i18n strings and which many other UIs are currently using uses positional.

**Comment by jamesarosen** [comment]
There's no built-in support for it, but here are some ideas.

Just try using numbers as parameter name:
```hbs
{{t 'some.string' 0='foo' 1=bar}}
```

If HTMLBars doesn't like that, you could do try doing all your translations in JS instead of HBS:
```js
someTranslatedProperty: Ember.computed('i18n.locale', 'bar', function() {
  return this.get('i18n').t('some.string', {
    0: 'foo',
    1: this.get('bar')
  });
})
```

The last option would be to swap in custom versions of some of the pieces of Ember-I18n to support positional parameters more directly. I'd start by writing a new helper:

```js
// app/helpers/t.js
import Ember from "ember";

export default Ember.Helper.extend({
  i18n: Ember.inject.service(),

  _locale: Ember.computed.reads('i18n.locale'),

  compute: function([ key, ...interpolations ]) {
    return this.get('i18n').t(key, interpolations);
  },

  _recomputeOnLocaleChange: Ember.observer('_locale', function() {
    this.recompute();
  })
});
```
That would let you write the following in a template:
```hbs
{{t 'some.string' 'foo' bar}}
```

That _might_ be enough, since `Em.get(['foo'], '0')` is `'foo'`.

**Comment by cfator** [comment]
Thank you for the quick feedback!
