### ISSUE TITLE
ember-i18n doesn't work with ember-composable-helpers

### ISSUE THREAD

**Issue by gossi** [jamesarosen/ember-i18n#374]
Hi,

I installed the [ember-composable-helpers](https://github.com/DockYard/ember-composable-helpers) and was about to use the string manipulation helpers with ember-i18n. I tried:

```
{{capitalize (t "edit")}}
```

which gives the error: `TypeError: str.replace is not a function`.

What's the proper way of making the both addons work together?
Thanks

**Comment by jamesarosen** [comment]
I think the problem is that the output of `t` is a `SafeString`, not a `String`. An easy way to them to work together would be to have a `to-s` helper:
```js
// app/helpers/to-s.js
export Ember.Helper.helper(function([ value ]) {
  return '' + value;
});
```
and
```hbs
{{capitalize (to-s (t "edit" ))}}
```
The problem with that is that if your translations include markup, it'll get escaped by Handlebars. So you'd need to add an `html-safe` helper` as well:
```js
// app/helpers/html-safe.js
export default Ember.Helper.helper(function([ value ]) {
  return Ember.String.htmlSafe(value);
});
```
and
```hbs
{{html-safe (capitalize (to-s (t "edit)))}}
```
A better solution would be for all the ember-composable-helpers helpers to understand string safety.

**Comment by jamesarosen** [comment]
One thing I've been considering is keeping the `escapeExpression` logic (escaping interpolations for XSS protection) in the translator, but moving the `htmlSafe` call (the thing that prevents double-escaping markup in your translations) into the helper. This would help scenarios where people are manipulating the results of translations inside components, routes, etc. But it wouldn't help here, since the unit of composition is the helper.

If I do that, though, I can also provide an _escape hatch_ (pun intended) for `{{t}}`:
```hbs
{{capitalize (t 'edit' html-safe=false)}}
```
Of course, if your `edit` translation has markup in it, you'll get double-escaping, but that's outside the scope of ember-i18n.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
