### ISSUE TITLE
Exclude locales from bundled app

### ISSUE THREAD

**Issue by jhilden** [jamesarosen/ember-i18n#405]
We have a whitelabel app with multiple locales that we build individually for each locale and serve from individual domains.  So the app itself is theoretically multilingual, but each instance only has a single locale and there is no way for the user to change it.  But since all translations live in `app/locales` they are always packaged for each build, resulting in an unnecessary increase of the production bundle.

Do you know of a way to exclude all but the currentLocale from each build?  (I realize that this might be more of a general ember-cli than a ember-i18n question, but I wanted to try it anyway)

Another use case for exluding locales could be if you start translating to a new locale that is not supposed to "go live" yet.

**Comment by jamesarosen** [comment]
> Do you know of a way to exclude all but the currentLocale from each build? 

I would use [broccoli-funnel](https://github.com/broccolijs/broccoli-funnel) to exclude those modules from the build.

One of the things I'm thinking about for ember-i18n 5.0 is moving more of the locale computation into build-time with Broccoli. It would be good to gather some information about how people want to customize that.

Which of the following are you trying to accomplish?

 1. a host `app.js` with no locale information that fetches `locales/en.js`, `locales/es.js`, etc. as they are needed at runtime
 2. a collection of localized `app-en.js`, `app-es.js`, etc. and using some sort of routing to serve the correct one to users
 3. other

**Comment by jhilden** [comment]
Thanks for your reply @jamesarosen 

> I would use broccoli-funnel to exclude those modules from the build.

Could you maybe point me in the right direction on how I would use that and how I would integrate it into ember-cli?


Concerning the direction for the upcoming ember-i18n:

1. sounds like a very simple solution that should be able to serve a wide range of use cases.  The additional HTTP request is not ideal, but since we are using HTTP2 it's really not an issue.

2. would not be a very good solution for us, since we have different builds for our different whitelabels (whith different stylesheets etc.) anyway.

The only other thing I could think of would be a configuration option that let's you configure which locales should be bundled in `app.js` (e.g. the defaultLocale) and which should be loaded separately.  But for simplicity reasons I would go straight with option 1.  :+1:

**Comment by jamesarosen** [comment]
> Could you maybe point me in the right direction on how I would use that and how I would integrate it into ember-cli?

First, I recommend reading [this StackOverflow question](http://stackoverflow.com/questions/30686368/exclude-folders-from-builds-in-brocfile) and [this article](https://dockyard.com/blog/2015/02/02/debugging-a-broccoli-tree) on how to debug a broccoli tree.

You'll need to create an addon (likely an in-repo addon) and manipulate the broccoli tree in `Addon.prototype.postprocessTree`:

```js
// lib/exclude-locales/index.js:
// exclude es and zh locales:
var Funnel = require('broccoli-funnel');

module.exports = {
  name: 'exclude-locales',

  isDevelopingAddon: function() {
    return true;
  },

  posprocessTree(type, tree) {
    if (type !== 'js') return tree;

    // exclude es and zh locales:
    return new Funnel(tree, {
      exclude: [
        'my-app/locales/es/translations.js',
        'my-app/locales/zh/translations.js'
      ]
    });
  }
};
```

It's a bit more complicated to write a broccoli filter that emits a `translations/*.js` file for each locale, but definitely possible. A first guess would be something like
```js
postProcessTree(type, tree) {
  if (type !== 'js') return tree;

  // exclude translation files from app.js:
  var treeWithoutLocales = new Funnel(tree, { exclude: [ 'my-app/locales/*/translations.js' ] });

  // emit separate locales/*.js files:
  var localesTree = new Funnel(tree, {
    include: [ 'my-app/locales/*/translations.js' ],

    destinationPath: function(relativePath) {
      const regex = /my-app\/locales\/(.+)\/translations\.js/;
      const locale = regex.exec(relativePath)[1];
      return 'translations/' + locale + '.js';
    }
  });

  // combine trees:
  var BroccoliMergeTrees = require('broccoli-merge-trees');
  return new BroccoliMergeTrees(treeWithoutLocales, localesTree);
}
```

I'm actually glad you asked me to go through this because it provides a good starting point for how we're going to do this in v5.0. I'd love it if you would document what you come up with on this issue :)

**Comment by jamesarosen** [comment]
In order to include _just_ `defaultLocale`, you need to exclude all the others and _include_ it. That's tricky in broccoli-funnel because `exclude` overrides `include`. So to include on `en`, you might try something like
```js
postprocessTree(type, tree) {
  if (type !== 'js') return tree;

  var treeWithoutLocales = new Funnel(tree, { exclude: [ 'my-app/locales/*/translations.js' ] });

  var treeWithEn = new Funnel(tree, {
    include: [ 'my-app/locales/en/translations.js' ]
  });


  // combine trees:
  var BroccoliMergeTrees = require('broccoli-merge-trees');
  return new BroccoliMergeTrees(treeWithoutLocales, localesTree);
}
```

If you want to use `defaultLocale` instead of `en` there, you can pull it off the app config:

```js
// lib/exclude-locales/index.js:
module.exports = {
  init: function() {
    this._super.init && this._super.init.apply(this, arguments);

    // not sure about how to get at this, but it's something like
    this.locale = this.app.config.i18n.defaultLocale;
  }
};
```
and then use `this.locale` in `postprocessTree`.

**Comment by PratheepV** [comment]
@jamesarosen 

I tried below code locales are skipping, but emitting to separate files are not working. Please help me.
```js
postprocessTree(type, tree) {
    if (type !== 'js') return tree;
    // exclude translation files from app.js:
    var treeWithoutLocales = new Funnel(tree, { exclude: [ 'my-app/locales/*/translations.js' ] });

    // emit separate locales/*.js files:
    var localesTree = new Funnel(tree, {
      include: [ 'my-app/locales/*/translations.js' ],

      getDestinationPath: function(relativePath) {
        const regex = /my-app\/locales\/(.+)\/translations\.js/;
        const locale = regex.exec(relativePath)[1];
        return 'translations/' + locale + '.js';
      }
    });

    return new BroccoliMergeTrees([treeWithoutLocales, localesTree]);
  }
```

**Comment by jamesarosen** [comment]
`postprocessTree` might be too late. Try `preprocessTree`.

**Comment by PratheepV** [comment]
@jamesarosen tried that one too, still, it's not separating.

**Comment by tehmaestro** [comment]
I'm trying to achieve the same thing.
Actually, I was thinking that the ideal solution would be to have something like this in `index.html`
```
    <script src="assets/vendor.js"></script>
    <script src="locales/translations.js"></script>
    <script src="assets/my-app.js"></script>
```

And keep the current `app/locales/fr/translations.js` structure.

This means I would need to do the following:
1. Ignore locales/** from build
2. Combine all locales into one translations.js
3. Make sure the translations is parsed by babel, so that the ES6 modules syntax is transpiled
4. Copy the translations file to `dist/locales`

I managed to do `1`, but the others seem kinda difficult.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
