### ISSUE TITLE
Passing in multiple translation keys (perhaps to Safely concat them together?)

### ISSUE THREAD

**Issue by devinrhode2** [jamesarosen/ember-i18n#471]
I've noticed a pattern where I'm joining together multiple translations together, for example: "Select" and either "Gender" or "State". It would be neat if we could do this:
```hbs
{{t "select" "gender"}}
{{!-- and then: --}}
{{t "select" "state"}}
```
Currently (..using v4.5.0) this code results in no errors, but just "Select" gets rendered for both.

I of course just use the `concat` helper but as I understand this does not keep the strings marked as htmlSafe, which could be nice. Also this style I'm suggesting is cleaner than my current method:
```hbs
(concat (t "select") " " (t "gender"))
```

**Comment by jamesarosen** [comment]
I like this idea!

**Comment by jamesarosen** [comment]
I guess I don't understand what you're trying to do.

```hbs
(concat (t "select") " " (t "gender"))
```
You're translating `select` and `gender` and then concatenating the results? What does that have to do with `"select"`?

**Comment by devinrhode2** [comment]
It's just a little be cleaner

**Comment by jamesarosen** [comment]
Now I understand. The concatenation is actually a bit of an i18n antipattern. See [10 Internationalization tips for developers – I18N checklist](http://www.emreakkas.com/internationalization/10-internationalization-tips-for-developers-i18n-checklist)

The problem is that "select" might translate differently based on whether the thing you're selecting ("gender", "state", "nation") is singular, plural, masculine, feminine, a proper noun, a common noun, or some other category.

I definitely recommend having translations for whole sentences or phrases: `{{t "select gender"}}` or `{{t 'select.gender'}}` or similar.

**Comment by devinrhode2** [comment]
Ahhh thank you James! Good to know!!

**Comment by devinrhode2** [comment]
So it's actually not a good idea to do `(t "select" "gender")` AND perhaps the library should issue a warning when a developer tries doing this, because if you are rendering a long list of options..

```hbs
{{#each options as |option|}}
  <p>{{t (concat "select." option)}}</p>
```
is not hard to do

**Comment by jamesarosen** [comment]
The `{{t}}` helper ignores any ordered arguments after the first, so `{{t "select" "gender"}}` is the same as `{{t "select"}}`. I'm all for a warning when passing more than one ordered argument if you want to make a PR.

**Comment by jamesarosen** [comment]
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).
